<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE omw:locations [
<!ELEMENT omw:locations (country)+>
<!ELEMENT country (region)+>
<!ELEMENT region (location)+>
<!ELEMENT location (#PCDATA)>
<!ATTLIST omw:locations xmlns:omw CDATA #REQUIRED>
<!ATTLIST country name CDATA #REQUIRED>
<!ATTLIST region name CDATA #REQUIRED>
<!ATTLIST location code CDATA #REQUIRED>
]>
<omw:locations xmlns:omw="https://garage.maemo.org/projects/omweather/">
<country name="AFGHANISTAN">
<region name="XX">
<location code="AFXX0002">HERAT</location>
<location code="AFXX0003">KABUL</location>
</region>
</country>
<country name="ALBANIA">
<region name="XX">
<location code="ALXX0002">TIRANA</location>
</region>
</country>
<country name="ALGERIA">
<region name="XX">
<location code="AGXX0001">ALGIERS</location>
<location code="AGXX0012">ANNABA</location>
<location code="AGXX0017">BATNA</location>
<location code="AGXX0003">BEJAIA</location>
<location code="AGXX0022">BISKARA</location>
<location code="AGXX0013">CONSTANTINE</location>
<location code="AGXX0006">ORAN</location>
<location code="AGXX0016">SETIF</location>
<location code="AGXX0018">TEBESSA</location>
<location code="AGXX0020">TIARET</location>
</region>
</country>
<country name="ANGOLA">
<region name="XX">
<location code="AOXX0008">LUANDA</location>
</region>
</country>
<country name="ANTARCTICA">
<region name="XX">
<location code="AYXX0010">MCMURDO ICE RNWY</location>
<location code="AYXX0007">BASE ARTURO PRAT</location>
<location code="AYXX0009">BASE BERNANDO O'HIGGINS</location>
<location code="AYXX0001">BASE ESPERANZA</location>
<location code="AYXX0003">BASE JUBANY</location>
<location code="AYXX0005">BASE MARAMBIO CENTRO MET. ANTARTICO</location>
<location code="AYXX0002">BASE ORCADAS</location>
<location code="AYXX0006">CENTRO MET. ANTARTICO</location>
<location code="AYXX0004">DIAMET-URUGUAY</location>
<location code="AYXX0008">GREAT WALL</location>
</region>
</country>
<country name="ARGENTINA">
<region name="XX">
<location code="ARBA0004">BAHIA BLANCA</location>
<location code="ARBA0009">BUENOS AIRES</location>
<location code="ARCC0013">CATAMARCA</location>
<location code="ARCT0021">COMODORO RIVADAVIA</location>
<location code="ARER0022">CONCORDIA</location>
<location code="ARCA0023">CORDOBA</location>
<location code="ARCS0025">CORRIENTES</location>
<location code="ARFA0030">FORMOSA</location>
<location code="ARBA0043">LA PLATA</location>
<location code="ARLR0045">LA RIOJA</location>
<location code="ARBA0054">MAR DEL PLATA</location>
<location code="ARMA0056">MENDOZA</location>
<location code="ARBA0057">MERCEDES</location>
<location code="ARRN0059">NEUQUEN</location>
<location code="ARSF0062">PARANA</location>
<location code="ARMS0118">POSADAS</location>
<location code="ARCO0072">RESISTENCIA AIRP</location>
<location code="ARCA0073">RIO CUARTO</location>
<location code="ARSF0078">ROSARIO</location>
<location code="ARSA0079">SALTA</location>
<location code="ARRN0081">SAN CARLOS DE BARILOCHE</location>
<location code="ARSJ0084">SAN JUAN</location>
<location code="ARCS0087">SAN LUIS</location>
<location code="ARMA0091">SAN RAFAEL</location>
<location code="ARER0093">SANTA FE</location>
<location code="ARSE0096">SANTIAGO DEL ESTERO</location>
<location code="ARBA0098">TANDIL</location>
</region>
</country>
<country name="ARMENIA">
<region name="XX">
<location code="AMXX0003">YEREVAN</location>
</region>
</country>
<country name="AUSTRALIA">
<region name="XX">
<location code="ASXX0001">ADELAIDE</location>
<location code="ASXX0016">BRISBANE</location>
<location code="ASXX0020">CAIRNS</location>
<location code="ASXX0023">CANBERRA</location>
<location code="ASXX0032">DARWIN</location>
<location code="ASXX0057">HOBART</location>
<location code="ASXX0331">LAUNCESTON AIRPO</location>
<location code="ASXX0075">MELBOURNE</location>
<location code="ASXX0089">PERTH</location>
<location code="ASXX0112">SYDNEY</location>
<location code="ASXX0117">TOWNSVILLE</location>
</region>
</country>
<country name="AUSTRIA">
<region name="XX">
<location code="AUXX0008">GRAZ</location>
<location code="AUXX0010">INNSBRUCK</location>
<location code="AUXX0016">LINZ</location>
<location code="AUXX0018">SALZBURG</location>
<location code="AUXX0025">VIENNA/SCHWECHAT</location>
<location code="AUXX0055">ZELTWEG</location>
</region>
</country>
<country name="AZERBAIJAN">
<region name="XX">
<location code="AJXX0001">BAKU/BINE ARPT</location>
<location code="AJXX0006">GYANDZHA</location>
</region>
</country>
<country name="BAHAMAS">
<region name="XX">
<location code="BFXX0005">NASSAU</location>
</region>
</country>
<country name="BANGLADESH">
<region name="XX">
<location code="BGXX0009">BOGRA</location>
<location code="BGXX0002">CHITTAGONG</location>
<location code="BGXX0003">DHAKA</location>
<location code="BGXX0004">JESSORE (CIV/MIL</location>
<location code="BGXX0010">SYLHET OSMANI</location>
</region>
</country>
<country name="BARBADOS">
<region name="XX">
<location code="BBXX0001">BRIDGETOWN CITY</location>
</region>
</country>
<country name="BELARUS">
<region name="XX">
<location code="BOXX0023">BREST</location>
<location code="BOXX0004">GOMEL</location>
<location code="BOXX0016">GRODNO</location>
<location code="BOXX0005">MINSK</location>
<location code="BOXX0018">MOGILEV</location>
<location code="BOXX0014">VITEBSK</location>
<location code="BOXX0019">KOSTJVKOVICI</location>
<location code="BOXX0013">LEPEL</location>
<location code="BOXX0012">LYNTUPY</location>
<location code="BOXX0006">MOZYR\'</location>
<location code="BOXX0026">MOZYR</location>
<location code="BOXX0025">ZITKOVICI</location>
<location code="BOXX0011">VERHNEDVINSK</location>
<location code="BOXX0001">BORISOV</location>
<location code="BOXX0021">SLUCK</location>
<location code="BOXX0002">DOBRUSH</location>
<location code="BOXX0022">BOBRUYSR</location>
<location code="BOXX0007">PINSK</location>
<location code="BOXX0003">DZERZHINSK</location>
<location code="BOXX0015">ORSA</location>
<location code="BOXX0017">LIDA</location>
<location code="BOXX0010">VETKA</location>
<location code="BOXX0020">BARANOVICI</location>
<location code="BOXX0008">RAKOV</location>
<location code="BOXX0009">RECHITSA</location>
</region>
</country>
<country name="BELGIUM">
<region name="XX">
<location code="BEXX0003">ANTWERP</location>
<location code="BEXX0005">BRUSSELS</location>
<location code="BEXX0006">CHARLEROI</location>
<location code="BEXX0008">GENT/INDUSTRY ZO</location>
<location code="BEXX0011">LIEGE</location>
</region>
</country>
<country name="BELIZE">
<region name="XX">
<location code="BHXX0002">BELMOPAN</location>
</region>
</country>
<country name="BENIN">
<region name="XX">
<location code="BNXX0001">COTONOU</location>
<location code="BNXX0003">SAVE</location>
</region>
</country>
<country name="BOLIVIA">
<region name="XX">
<location code="BLXX0003">COCHABAMBA</location>
<location code="BLXX0006">LA PAZ</location>
<location code="BLXX0025">ORURO</location>
<location code="BLXX0008">POTOSI</location>
<location code="BLXX0035">SANTA CRUZ</location>
<location code="BLXX0013">SUCRE</location>
<location code="BLXX0015">TARIJA</location>
</region>
</country>
<country name="BOTSWANA">
<region name="XX">
<location code="BCXX0004">FRANCISTOWN</location>
<location code="BCXX0001">GABORONE</location>
</region>
</country>
<country name="BRAZIL">
<region name="XX">
<location code="BRXX0007">ANAPOLIS (BRAZ-A</location>
<location code="BRXX0011">ARACAJU/SANTA MA</location>
<location code="BRXX0013">ARACATUBA</location>
<location code="BRXX0265">ARARAQUARA</location>
<location code="BRXX0026">BARBACENA (CIV/M</location>
<location code="BRXX0031">BAURU</location>
<location code="BRXX0032">BELEM</location>
<location code="BRXX0033">BELO HORIZONTE</location>
<location code="BRXX0038">BOA VISTA</location>
<location code="BRXX0043">BRASILIA</location>
<location code="BRXX0045">CABO FRIO</location>
<location code="BRXX0049">CAMPINA GRANDE</location>
<location code="BRXX0050">CAMPINAS</location>
<location code="BRXX0051">CAMPO GRANDE</location>
<location code="BRXX0054">CAMPOS</location>
<location code="BRXX0727">CARIACICA</location>
<location code="BRXX0063">CASCAVEL</location>
<location code="BRXX0068">CAXIAS DO SUL</location>
<location code="BRXX0069">CHAPECO</location>
<location code="BRXX0078">CUIABA</location>
<location code="BRXX0079">CURITIBA</location>
<location code="BRXX0087">DUQUE DE CAXIAS</location>
<location code="BRXX0553">EMBU</location>
<location code="BRXX0089">FEIRA DE SANTANA</location>
<location code="BRXX0705">FERRAZ DE VASCONCELOS</location>
<location code="BRXX0091">FLORIANOPOLIS</location>
<location code="BRXX0093">FORTALEZA</location>
<location code="BRXX0094">FOZ DO IGUACU</location>
<location code="BRXX0095">FRANCA</location>
<location code="BRXX0559">FRANCISCO MORATO</location>
<location code="BRXX0560">FRANCO DA ROCHA</location>
<location code="BRXX0096">GARANHUNS</location>
<location code="BRXX0099">GOIANIA</location>
<location code="BRXX0100">GOVERNADOR VALADARES</location>
<location code="BRXX0280">GRAVATAI</location>
<location code="BRXX0104">GUARAPUAVA</location>
<location code="BRXX0281">GUARUJA</location>
<location code="BRXX0107">GUARULHOS</location>
<location code="BRXX0283">ILHEUS</location>
<location code="BRXX0566">IMPERATRIZ</location>
<location code="BRXX0567">INDAIATUBA</location>
<location code="BRXX0112">IPATINGA</location>
<location code="BRXX0393">ITABORAI</location>
<location code="BRXX0285">ITABUNA</location>
<location code="BRXX0115">ITAJAI</location>
<location code="BRXX0576">ITAPECERICA DA SERRA</location>
<location code="BRXX0287">ITAPETININGA</location>
<location code="BRXX0117">ITAPEVI</location>
<location code="BRXX0121">ITU</location>
<location code="BRXX0398">JACAREI</location>
<location code="BRXX0126">JARAGUA DO SUL</location>
<location code="BRXX0364">JAU</location>
<location code="BRXX0289">JEQUIE</location>
<location code="BRXX0128">JOAO PESSOA</location>
<location code="BRXX0130">JOINVILLE</location>
<location code="BRXX0290">JUAZEIRO</location>
<location code="BRXX0290">JUAZEIRO DO NORTE</location>
<location code="BRXX0131">JUIZ DE FORA</location>
<location code="BRXX2337">JUNDIAI</location>
<location code="BRXX0291">LAGES</location>
<location code="BRXX0134">LIMEIRA</location>
<location code="BRXX0137">LONDRINA</location>
<location code="BRXX0140">LUZIANIA</location>
<location code="BRXX0143">MACAE</location>
<location code="BRXX0142">MACAPA</location>
<location code="BRXX0143">MACEIO</location>
<location code="BRXX0145">MAGE</location>
<location code="BRXX0146">MANAUS</location>
<location code="BRXX0149">MARABA</location>
<location code="BRXX0294">MARACANAU</location>
<location code="BRXX0150">MARILIA</location>
<location code="BRXX0151">MARINGA</location>
<location code="BRXX0152">MAUA</location>
<location code="BRXX0297">MOGI GUACU</location>
<location code="BRXX0296">MOJI DAS CRUZES</location>
<location code="BRXX0155">MONTES CLAROS</location>
<location code="BRXX0157">MOSSORO</location>
<location code="BRXX0158">NATAL</location>
<location code="BRXX0299">NILOPOLIS</location>
<location code="BRXX0159">NITEROI</location>
<location code="BRXX2716">NOVA FRIBURGO</location>
<location code="BRXX0161">NOVA IGUACU</location>
<location code="BRXX0163">NOVO HAMBURGO</location>
<location code="BRXX0164">OLINDA</location>
<location code="BRXX0165">OSASCO</location>
<location code="BRXX0169">PALMAS</location>
<location code="BRXX0172">PARANAGUA</location>
<location code="BRXX0301">PARNAIBA</location>
<location code="BRXX0174">PASSO FUNDO</location>
<location code="BRXX0302">PATOS DE MINAS</location>
<location code="BRXX0304">PAULISTA</location>
<location code="BRXX0176">PELOTAS</location>
<location code="BRXX0179">PETROLINA</location>
<location code="BRXX0180">PETROPOLIS</location>
<location code="BRXX0639">PINDAMONHANGABA</location>
<location code="BRXX3902">PINHAIS</location>
<location code="BRXX0181">PIRACICABA</location>
<location code="BRXX0184">PONTA GROSSA</location>
<location code="BRXX0186">PORTO ALEGRE</location>
<location code="BRXX0190">PORTO VELHO</location>
<location code="BRXX3088">PRAIA GRANDE</location>
<location code="BRXX0192">PRESIDENTE PRUDENTE</location>
<location code="BRXX0652">QUEIMADOS</location>
<location code="BRXX0195">RECIFE</location>
<location code="BRXX0197">RESENDE</location>
<location code="BRXX3187">RIBEIRAO DAS NEVES</location>
<location code="BRXX0436">RIBEIRAO PIRES</location>
<location code="BRXX0198">RIBEIRAO PRETO</location>
<location code="BRXX0199">RIO BRANCO</location>
<location code="BRXX3201">RIO CLARO</location>
<location code="BRXX0201">RIO DE JANEIRO</location>
<location code="BRXX0202">RIO GRANDE</location>
<location code="BRXX0205">RIO VERDE</location>
<location code="BRXX0207">RONDONOPOLIS</location>
<location code="BRXX0211">SABARA</location>
<location code="BRXX3272">SALVADOR</location>
<location code="BRXX0443">SANTA BARBARA D'OESTE</location>
<location code="BRXX0666">SANTA LUZIA</location>
<location code="BRXX0215">SANTA MARIA</location>
<location code="BRXX0217">SANTO ANDRE</location>
<location code="BRXX3386">SANTOS</location>
<location code="BRXX0220">SAO BERNARDO DO CAMPO</location>
<location code="BRXX0438">SAO CAETANO DO SUL</location>
<location code="BRXX0222">SAO CARLOS</location>
<location code="BRXX0447">SAO GONCALO</location>
<location code="BRXX0722">SAO JOAO DE MERITI</location>
<location code="BRXX0440">SAO JOSE</location>
<location code="BRXX0227">SAO JOSE DO RIO PRETO</location>
<location code="BRXX0228">SAO JOSE DOS CAMPOS</location>
<location code="BRXX0229">SAO JOSE DOS PINHAIS</location>
<location code="BRXX0230">SAO LEOPOLDO</location>
<location code="BRXX0231">SAO LUIS</location>
<location code="BRXX0232">SAO PAULO</location>
<location code="BRXX0233">SAO VICENTE</location>
<location code="BRXX0234">SERRA</location>
<location code="BRXX0235">SETE LAGOAS</location>
<location code="BRXX0312">SOBRAL</location>
<location code="BRXX0237">SOROCABA</location>
<location code="BRXX0313">SUMARE</location>
<location code="BRXX0670">SUZANO</location>
<location code="BRXX0463">TABOAO DA SERRA</location>
<location code="BRXX0242">TAUBATE</location>
<location code="BRXX0314">TEOFILO OTONI</location>
<location code="BRXX0245">TERESINA</location>
<location code="BRXX0315">TERESOPOLIS</location>
<location code="BRXX0316">TIMON</location>
<location code="BRXX0252">UBERABA</location>
<location code="BRXX0253">UBERLANDIA</location>
<location code="BRXX0254">URUGUAIANA</location>
<location code="BRXX0318">VARGINHA</location>
<location code="BRXX0255">VARZEA GRANDE</location>
<location code="BRXX0257">VIAMAO</location>
<location code="BRXX0319">VILA VELHA</location>
<location code="BRXX0259">VITORIA</location>
<location code="BRXX0260">VITORIA DA CONQUISTA</location>
<location code="BRXX0259">VITORIA DE SANTO ANTAO</location>
<location code="BRXX0320">VOLTA REDONDA</location>
<location code="VIXX0001">BEEF ISL/ROADTOW</location>
</region>
</country>
<country name="BULGARIA">
<region name="XX">
<location code="BUXX0001">BURGAS</location>
<location code="BUXX0003">PLEVEN</location>
<location code="BUXX0004">PLOVDIV</location>
<location code="BUXX0011">RUSE</location>
<location code="BUXX0005">SOFIA</location>
<location code="BUXX0006">STARA ZAGORA</location>
<location code="BUXX0007">VARNA</location>
<location code="UVXX0001">OUAGADOUGOU (MIL</location>
</region>
</country>
<country name="BURUNDI">
<region name="XX">
<location code="BYXX0001">BUJUMBURA</location>
</region>
</country>
<country name="CAMBODIA">
<region name="XX">
<location code="CBXX0001">PHNOM-PENH/POCHE</location>
</region>
</country>
<country name="CAMEROON">
<region name="XX">
<location code="CMXX0003">DOUALA (CIV/MIL)</location>
<location code="CMXX0008">YAOUNDE</location>
</region>
</country>
<country name="CANADA">
<region name="XX">
<location code="CAXX0001">ABBOTSFORD</location>
<location code="CAXX0043">BRAMPTON</location>
<location code="CAXX0050">BURLINGTON</location>
<location code="CAXX0051">BURNABY</location>
<location code="CAXX0054">CALGARY</location>
<location code="CAXX0056">CAMBRIDGE</location>
<location code="CAXX0126">EDMONTON</location>
<location code="CAXX0158">GATINEAU</location>
<location code="CAXX0181">GUELPH</location>
<location code="CAXX0183">HALIFAX</location>
<location code="CAXX0184">HAMILTON</location>
<location code="CAXX0227">KITCHENER</location>
<location code="CAXX0243">LAVAL</location>
<location code="CAXX0255">LONDON</location>
<location code="CAXX0257">LONGUEUIL</location>
<location code="CAXX0273">MARKHAM</location>
<location code="CAXX0295">MISSISSAUGA</location>
<location code="CAXX0301">MONTREAL</location>
<location code="CAXX0333">OAKVILLE</location>
<location code="CAXX0342">OSHAWA</location>
<location code="CAXX0343">OTTAWA</location>
<location code="CAXX0385">QUEBEC</location>
<location code="CAXX0397">REGINA</location>
<location code="CAXX0400">RICHMOND</location>
<location code="CAXX0401">RICHMOND HILL</location>
<location code="CAXX0412">SAANICH</location>
<location code="CAXX0416">SAINT CATHARINES</location>
<location code="CAXX0442">SASKATOON</location>
<location code="CAXX0485">SURREY</location>
<location code="CAXX0498">THUNDER BAY</location>
<location code="CAXX0504">TORONTO</location>
<location code="CAXX0518">VANCOUVER</location>
<location code="CAXX0546">WINDSOR</location>
<location code="CAXX0547">WINNIPEG</location>
<location code="CVXX0002">PRAIA</location>
<location code="CJXX0001">GEORGE TOWN</location>
<location code="CTXX0001">BANGUI/M'POKO (M</location>
</region>
</country>
<country name="CHAD">
<region name="XX">
<location code="CDXX0003">N'DJAMENA</location>
</region>
</country>
<country name="CHILE">
<region name="XX">
<location code="CIXX0001">ANTOFAGASTA</location>
<location code="CIXX0002">ARICA</location>
<location code="CIXX0033">CALAMA</location>
<location code="CIXX0006">CHILLAN</location>
<location code="CIXX0007">CONCEPCION</location>
<location code="CIXX0030">COPIAPO</location>
<location code="CIXX0008">COQUIMBO</location>
<location code="CIXX0031">CURICO</location>
<location code="CIXX0009">IQUIQUE</location>
<location code="CIXX0010">LA SERENA</location>
<location code="CIXX0012">OSORNO</location>
<location code="CIXX0013">OVALLE</location>
<location code="CIXX0015">PUERTO MONTT</location>
<location code="CIXX0017">PUNTA ARENAS</location>
<location code="CIXX0018">RANCAGUA</location>
<location code="CIXX0019">SAN BERNARDO</location>
<location code="CIXX0020">SANTIAGO</location>
<location code="CIXX0021">TALCA</location>
<location code="CIXX0022">TALCAHUANO</location>
<location code="CIXX0023">TEMUCO</location>
<location code="CIXX0025">VALDIVIA</location>
<location code="CIXX0027">VINA DEL MAR</location>
</region>
</country>
<country name="CHINA">
<region name="XX">
<location code="CHXX0001">ACHENG</location>
<location code="CHXX0187">ANDA</location>
<location code="CHXX0394">ANKANG</location>
<location code="CHXX0452">ANQING</location>
<location code="CHXX0004">ANSHAN</location>
<location code="CHXX0005">ANSHUN</location>
<location code="CHXX0269">ANYANG</location>
<location code="CHXX0006">BAIYIN</location>
<location code="CHXX0308">BAODING</location>
<location code="CHXX0387">BAOJI</location>
<location code="CHXX0370">BAOSHAN</location>
<location code="CHXX0007">BAOTOU</location>
<location code="CHXX0499">BEIHAI</location>
<location code="CHXX0008">BEIJING</location>
<location code="CHXX0444">BENGBU</location>
<location code="CHXX0296">BENXI</location>
<location code="CHXX0010">CHANGCHUN</location>
<location code="CHXX0416">CHANGDE</location>
<location code="CHXX0011">CHANGJI</location>
<location code="CHXX0013">CHANGSHA</location>
<location code="CHXX0015">CHANGZHOU</location>
<location code="CHXX0294">CHAOYANG</location>
<location code="CHXX0302">CHENGDE</location>
<location code="CHXX0016">CHENGDU</location>
<location code="CHXX0435">CHENZHOU</location>
<location code="CHXX0286">CHIFENG</location>
<location code="CHXX0017">CHONGQING</location>
<location code="CHXX0371">DALI</location>
<location code="CHXX0019">DALIAN</location>
<location code="CHXX0306">DANDONG</location>
<location code="CHXX0251">DATONG</location>
<location code="CHXX0445">DONGTAI</location>
<location code="CHXX0284">DUNHUA</location>
<location code="CHXX0026">FENGCHENG</location>
<location code="CHXX0028">FOSHAN</location>
<location code="CHXX0029">FUSHUN</location>
<location code="CHXX0442">FUYANG</location>
<location code="CHXX0031">FUZHOU</location>
<location code="CHXX0436">GANZHOU</location>
<location code="CHXX0037">GUANGZHOU</location>
<location code="CHXX0434">GUILIN</location>
<location code="CHXX0039">GUIYANG</location>
<location code="CHXX0041">HAICHENG</location>
<location code="CHXX0502">HAIKOU</location>
<location code="CHXX0175">HAILAR</location>
<location code="CHXX0183">HAILUN</location>
<location code="CHXX0219">HAMI</location>
<location code="CHXX0043">HANGU</location>
<location code="CHXX0044">HANGZHOU</location>
<location code="CHXX0390">HANZHONG</location>
<location code="CHXX0046">HARBIN</location>
<location code="CHXX0448">HEFEI</location>
<location code="CHXX0045">HENGYANG</location>
<location code="CHXX0249">HOHHOT</location>
<location code="CHXX0049">HONG KONG</location>
<location code="CHXX0290">HUADIAN</location>
<location code="CHXX0051">HUANGSHI</location>
<location code="CHXX0053">HUIZHOU</location>
<location code="CHXX0054">HULAN</location>
<location code="CHXX0056">HUZHOU</location>
<location code="CHXX0058">JIANGMEN</location>
<location code="CHXX0062">JIAXING</location>
<location code="CHXX0063">JILIN</location>
<location code="CHXX0064">JINAN</location>
<location code="CHXX0457">JINGDEZHEN</location>
<location code="CHXX0250">JINING</location>
<location code="CHXX0067">JINZHOU</location>
<location code="CHXX0068">JIUJIANG</location>
<location code="CHXX0069">JIUTAI</location>
<location code="CHXX0193">JIXI</location>
<location code="CHXX0072">KAIFENG</location>
<location code="CHXX0200">KARAMAY</location>
<location code="CHXX0074">KASHI</location>
<location code="CHXX0209">KORLA</location>
<location code="CHXX0075">KOWLOON</location>
<location code="CHXX0076">KUNMING</location>
<location code="CHXX0079">LANZHOU</location>
<location code="CHXX0081">LIAOYANG</location>
<location code="CHXX0463">LINHAI</location>
<location code="CHXX0253">LINHE</location>
<location code="CHXX0281">LINXI</location>
<location code="CHXX0461">LISHUI</location>
<location code="CHXX0479">LIUZHOU</location>
<location code="CHXX0080">LHASA</location>
<location code="CHXX0086">LUOYANG</location>
<location code="CHXX0088">LUZHOU</location>
<location code="CHXX0403">MACHENG</location>
<location code="CHXX0090">MAOMING</location>
<location code="CHXX0351">MIANYANG</location>
<location code="CHXX0093">MINHANG</location>
<location code="CHXX0278">MUDANJIANG</location>
<location code="CHXX0097">NANCHANG</location>
<location code="CHXX0098">NANCHONG</location>
<location code="CHXX0099">NANJING</location>
<location code="CHXX0100">NANNING</location>
<location code="CHXX0471">NANPING</location>
<location code="CHXX0101">NANTONG</location>
<location code="CHXX0391">NANYANG</location>
<location code="CHXX0103">NEIJIANG</location>
<location code="CHXX0270">PINGLIANG</location>
<location code="CHXX0110">QINGDAO</location>
<location code="CHXX0289">QINGYUAN</location>
<location code="CHXX0112">QIQIHAR</location>
<location code="CHXX0114">QUANZHOU</location>
<location code="CHXX0322">RIZHAO</location>
<location code="CHXX0116">SHANGHAI</location>
<location code="CHXX0493">SHANTOU</location>
<location code="CHXX0496">SHANWEI</location>
<location code="CHXX0482">SHAOGUAN</location>
<location code="CHXX0466">SHAOWU</location>
<location code="CHXX0117">SHAOXING</location>
<location code="CHXX0422">SHAOYANG</location>
<location code="CHXX0118">SHASHI</location>
<location code="CHXX0119">SHENYANG</location>
<location code="CHXX0120">SHENZHEN</location>
<location code="CHXX0122">SHIJIAZHUANG</location>
<location code="CHXX0124">SHUANGCHENG</location>
<location code="CHXX0283">SIPING</location>
<location code="CHXX0127">SUINING</location>
<location code="CHXX0129">TAIYUAN</location>
<location code="CHXX0130">TANGGU</location>
<location code="CHXX0131">TANGSHAN</location>
<location code="CHXX0133">TIANJIN</location>
<location code="CHXX0134">TIELING</location>
<location code="CHXX0282">TONGLIAO</location>
<location code="CHXX0135">URUMQI</location>
<location code="CHXX0318">WEIFANG</location>
<location code="CHXX0137">WEINAN</location>
<location code="CHXX0462">WENZHOU</location>
<location code="CHXX0138">WUHAN</location>
<location code="CHXX0449">WUHU</location>
<location code="CHXX0490">WUZHOU</location>
<location code="CHXX0140">XIAMEN</location>
<location code="CHXX0141">XIAN</location>
<location code="CHXX0142">XIANGTAN</location>
<location code="CHXX0143">XIANYANG</location>
<location code="CHXX0144">XIAOGAN</location>
<location code="CHXX0363">XICHANG</location>
<location code="CHXX0266">XINGTAI</location>
<location code="CHXX0236">XINING</location>
<location code="CHXX0148">XINXIANG</location>
<location code="CHXX0149">XINYANG</location>
<location code="CHXX0437">XUZHOU</location>
<location code="CHXX0500">YANGJIANG</location>
<location code="CHXX0152">YANGQUAN</location>
<location code="CHXX0291">YANJI</location>
<location code="CHXX0362">YIBIN</location>
<location code="CHXX0407">YICHANG</location>
<location code="CHXX0154">YIDU</location>
<location code="CHXX0259">YINCHUAN</location>
<location code="CHXX0304">YINGKOU</location>
<location code="CHXX0203">YINING</location>
<location code="CHXX0156">YIYANG</location>
<location code="CHXX0160">YUCI</location>
<location code="CHXX0411">YUEYANG</location>
<location code="CHXX0260">YULIN</location>
<location code="CHXX0272">YUNCHENG</location>
<location code="CHXX0334">YUSHU</location>
<location code="CHXX0397">ZAOYANG</location>
<location code="CHXX0300">ZHANGJIAKOU</location>
<location code="CHXX0228">ZHANGYE</location>
<location code="CHXX0162">ZHANGZHOU</location>
<location code="CHXX0163">ZHANJIANG</location>
<location code="CHXX0364">ZHAOTONG</location>
<location code="CHXX0165">ZHENGZHOU</location>
<location code="CHXX0166">ZHENJIANG</location>
<location code="CHXX0167">ZHOUCUN</location>
<location code="CHXX0398">ZHUMADIAN</location>
<location code="CHXX0168">ZHUZHOU</location>
<location code="CHXX0419">ZUNYI</location>
</region>
</country>
<country name="COLUMBIA">
<region name="XX">
<location code="COXX0001">ARMENIA</location>
<location code="COXX0006">BARRANCABERMEJA</location>
<location code="COXX0002">BARRANQUILLA</location>
<location code="COXX0003">BELLO</location>
<location code="COXX0004">BOGOTA</location>
<location code="COXX0005">BUCARAMANGA</location>
<location code="COXX0007">BUENAVENTURA</location>
<location code="COXX0008">CALI</location>
<location code="COXX0009">CARTAGENA</location>
<location code="COXX0010">CARTAGO</location>
<location code="COXX0011">CUCUTA</location>
<location code="COXX0012">ENVIGADO</location>
<location code="COXX0013">FLORIDABLANCA</location>
<location code="COXX0014">GIRARDOT</location>
<location code="COXX0015">IBAGUE</location>
<location code="COXX0017">ITAGUI</location>
<location code="COXX0019">MANIZALES</location>
<location code="COXX0020">MEDELLIN</location>
<location code="COXX0021">MONTERIA</location>
<location code="COXX0037">NEIVA</location>
<location code="COXX0022">PALMIRA</location>
<location code="COXX0023">PASTO</location>
<location code="COXX0024">PEREIRA</location>
<location code="COXX0025">POPAYAN</location>
<location code="COXX0028">SANTA MARTA</location>
<location code="COXX0029">SINCELEJO</location>
<location code="COXX0030">SOGAMOSO</location>
<location code="COXX0031">SOLEDAD</location>
<location code="COXX0033">TUNJA</location>
<location code="COXX0038">VALLEDUPAR</location>
<location code="COXX0034">VILLAVICENCIO</location>
</region>
</country>
<country name="COMOROS">
<region name="XX">
<location code="CNXX0003">MORONI/HAHAIA IN</location>
<location code="CWXX0001">RAROTONGA</location>
<location code="CSXX0009">SAN JOSE</location>
<location code="IVXX0001">ABIDJAN/PORT BOU</location>
<location code="IVXX0002">DABOU</location>
<location code="IVXX0004">GAGNOA</location>
<location code="IVXX0003">GRAND-BASSAM</location>
</region>
</country>
<country name="CROATIA">
<region name="XX">
<location code="HRXX0006">RIJEKA</location>
<location code="HRXX0004">SPLIT</location>
<location code="HRXX0005">ZAGREB</location>
</region>
</country>
<country name="CUBA">
<region name="XX">
<location code="CUXX0001">BAYAMO</location>
<location code="CUXX0002">CAMAGUEY</location>
<location code="CUXX0017">CIENFUEGOS</location>
<location code="CUXX0003">HAVANA</location>
<location code="CUXX0011">HOLGUIN</location>
<location code="CUXX0004">LAS TUNAS</location>
<location code="CUXX0005">MANZANILLO</location>
<location code="CUXX0006">MATANZAS</location>
<location code="CUXX0007">PINAR DEL RIO</location>
<location code="CUXX0008">SANCTI SPIRITUS</location>
<location code="CUXX0009">SANTA CLARA</location>
<location code="CUXX0010">SANTIAGO DE CUBA</location>
</region>
</country>
<country name="CYPRUS">
<region name="XX">
<location code="CYXX0005">NICOSIA</location>
<location code="EZXX0002">BRNO</location>
<location code="EZXX0009">OSTRAVA</location>
<location code="EZXX0010">PLZEN</location>
<location code="EZXX0012">PRAGUE/RUZYNE</location>
<location code="CGXX0002">BOMA</location>
<location code="CGXX0017">KANANGA</location>
<location code="CGXX0005">KINSHASA</location>
<location code="CGXX0007">KISANGANI</location>
<location code="CGXX0008">LIKASI</location>
<location code="CGXX0009">LUBUMBASHI</location>
<location code="CGXX0010">MATADI</location>
<location code="CGXX0011">MBANDAKA</location>
<location code="CGXX0014">UVIRA</location>
</region>
</country>
<country name="DENMARK">
<region name="XX">
<location code="DAXX0002">AALBORG</location>